### PR TITLE
Remove predicate

### LINKED ISSUE #32: Review the predicate/offers done logic
When creating an app, a predicate function can be passed to let the dev decide criteria on which a swap should be accepted or declined.

https://github.com/comit-network/hello-swap/blob/0c4fbc9db01363ba16f8c8ca16f21f660e85ddce/src/helloSwap.ts#L77

There is also an `offersMade` property that stored offers made and should (but is not) be used to know whether to accept or decline offers.

https://github.com/comit-network/hello-swap/blob/0c4fbc9db01363ba16f8c8ca16f21f660e85ddce/src/helloSwap.ts#L81

Instead, I propose to trash the predicate and ensure that `offersMade` is used.
If an offer is made, then it should be accepted automatically and that should be the only logic to automatically accept/decline offers.

### PR DESCRIPTION
**Pull request by D4nte**
I did not follow the issue instructions in purpose.

It know accepts any swap and do not remember offers make.

I adopted the "hello world" mindset. This should be as simple as possible and the simplest way is to accept all.

Resolves #32.

### CODE REVIEW

**Review by luckysori — APPROVED** [review]
Looks good to me!

**Review by da-kami — APPROVED** [review]
nice, 

Id' be keen to remove this part as well, because it does not really add any value (as there is no way for the user to change it anyway) and makes it complicated to change Hallo World to ETH->BTC.

https://github.com/comit-network/hello-swap/blob/71296cceae5b679e60d3b158cb063c7d4afe1dfa/src/helloSwap.ts#L156-L165

keen to do it in this PR or create a separate issue?

**Review by thomaseizinger — APPROVED** [review]
Fine with me :)
@bonomat any objections?

**Comment by D4nte** [comment]
> nice,
> 
> Id' be keen to remove this part as well, because it does not really add any value (as there is no way for the user to change it anyway) and makes it complicated to change Hallo World to ETH->BTC.
> 
> https://github.com/comit-network/hello-swap/blob/71296cceae5b679e60d3b158cb063c7d4afe1dfa/src/helloSwap.ts#L156-L165
> 
> keen to do it in this PR or create a separate issue?

Separate PR please :)

**Pull request merged**
